global:
  resolve_timeout: 1m

route:
  receiver: 'discord'
  group_by: ['alertname', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h

receivers:
  - name: 'discord'
    webhook_configs:
      - url: 'http://discord-webhook:9094'
        send_resolved: true
